### ISSUE TITLE
Improvment on usages of Optional, Stream and lambdas

### ISSUE THREAD

**Issue by NicolasLambert** [Clayton7510/RuleBook#12]
Hi Clayton,

Usage of Java8 features (especially Optional) can be improved.
I suggest you to put an eye on this article :
https://dzone.com/articles/optional-ispresent-is-bad-for-you

Also you should consider returning Optional in your API when the attribute can be null (like next rule).

Again, great work !

**Comment by Clayton7510** [comment]
Thanks for the suggestion, Nicolas. You're right! Some of the usage of those features can be cleaned up.

**Comment by NicolasLambert** [comment]
And here is my corresponding PR to fix it : #11 
I hope that I followed all your contribution rules.

**Comment by Clayton7510** [comment]
Thanks, Nicholas. I'll check it out.
