### ISSUE TITLE
Multiple invocations of RuleBook.run() could define rules more than once

### ISSUE THREAD

**Issue by Clayton7510** [Clayton7510/RuleBook#26]
Practically, this shouldn't be a huge issue since RuleBooks are likely instantiated each time they are to be used (Spring does this with prototype) and therefore run() would likely only be called once per RuleBook instance. However, if a developer wanted to create a single instantiation of a RuleBook class and re-run it then there could be an issue with rules running multiple times unintentionally. This should be corrected in a minor release.

**Comment by wheezymustafa** [comment]
This is my current use case.  I am generating singleton RuleBookBeans at initialization and accessing them via a factory, where based on certain conditions, i retrieve one of those specific rulebooks and execute the rules against the object.

**Comment by Clayton7510** [comment]
@wheezymustafa I would recommend making RuleBookBeans prototypes instead of Singletons. 
There are 2 reasons for using prototype over singleton with RuleBookBeans:
1. In the current release, declared rules are added to RuleBooks in the run() method. So, by using the same instance, every time you call the run() method, you would be adding the same rules again. (This should be fixed in Issue26 branch tho).
2. The state of the Result (if you are using a Result) and Facts are referenced in the BuleBookBean (and all current RuleBook implementations). So, every time you run the same RuleBook instance (as is the case with a Singleton), any Facts that were changed and propagated down the rule chain, will be changed again. The same applies for the Result. You may want this behavior. But in most cases, I'd think that you wouldn't. Given that, making RuleBookBean a prototype is probably the way to go.

**Comment by Clayton7510** [comment]
This fix is now available in the 0.3.1-SNAPSHOT Release.
