### ISSUE TITLE
Passing a Collection (Map,List) as Given shows up as null in rule?

### ISSUE THREAD

**Issue by wheezymustafa** [Clayton7510/RuleBook#30]
You can tell me if I'm just not using it correctly, but --

If I pass a single POJO as Given, I retrieve the List<Object> in my rule and process it as normal, as your documentation states.  However, trying to pass a collection seems to result in the object either being swallowed up and spit out as null, or as an empty List.  I can provide an example if needed.

**Comment by Clayton7510** [comment]
I don't know if I am understanding exactly what you are trying to do. So, I will explain the approaches you can use to inject complex objects into POJO Rules. As you know if you annotate a List with a @Given annotation and no value, it will inject that list with all the Facts given to the RuleBook of the generic type of the list. But POJO Rules will only do that with Lists and only when there is a @Given annotated on that List where (1) the @Given has no value passed to it and (2) the List has a generic type that matches at least one Fact given to the RuleBook.

Now, say you have an entire Map that you want to pass into the POJO Rule. You could give that Map as a Fact to the RuleBook that runs the rule (e.g. Fact<Map>). Let's say the name of that Fact is "myMap", then the following code should inject that Map into the POJO Rule:

@Given("myMap")
Map<GenericType1, GenericType2> map;

or you could do

@Given("myMap")
Fact<Map<GenericType1, GenericType2>> myMapInFact;

As I refer to the Spring examples, I see there are some errata. So, I will get that corrected (probably tomorrow). 

If this doesn't answer your question, then please attach the code in question and I will take a look and give you feedback.

**Comment by Clayton7510** [comment]
Errata in the Spring examples should be corrected now.

**Comment by wheezymustafa** [comment]
Hello,

Your explanation did the trick - I was able to get through my road blocks.  Thanks for the information!

**Comment by Clayton7510** [comment]
You're welcome! I'm gals you got everything working out.

BTW, I am planning on having RuleBook support auto-injection into other Collection types the way it does with List. The solution just looked a little less elegant. So, it's omitted currently. But I do agree that it would be a useful feature to have.

**Comment by Clayton7510** [comment]
The more I thought about it, the more I realized that there should be support for injection into Collection interfaces. So, 0.3.2-SNAPSHOT on Sonatype now injects Map, List, Set and FactMap the same way only List was injected. It will inject any Fact value objects where their types match up to the generic type of the collection in a POJO Rule where @Given has no value.
